Fix build by adding libacl and libncurses
eclipse-iceoryx/iceoryx-project-template pull request #4
Opened 2022-06-03 12:01 UTC by elBoberido

## Pre-Review Checklist for the PR Author

1. [x] Code is formatted with clang-format
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed
1. [x] Assign PR to reviewer

## Notes for Reviewer

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- none

2022-06-03 12:03 UTC, dkroenke commented on .github/workflows/build.yml
> +        run: apt-get update && apt-get install -y libacl1-dev libncurses5-dev
```suggestion
        run: sudo apt-get update && apt-get install -y libacl1-dev libncurses5-dev
```

2022-06-03 12:04 UTC, mossmaurice approved these changes

2022-06-03 12:05 UTC, mossmaurice requested changes
https://img.devrant.com/devrant/rant/r_1902819_KMYZA.jpg

2022-06-03 12:07 UTC, mossmaurice commented
> Commits are properly organized and messages are according to the guideline

Do we follow the usual guidelines in this repo, too?

2022-06-03 12:12 UTC, dkroenke approved these changes

2022-06-03 12:14 UTC, elBoberido commented
> > Commits are properly organized and messages are according to the guideline
> 
> Do we follow the usual guidelines in this repo, too?

@mossmaurice yes, I squashed the `Fix fix` and `Fix fix fix` after the fix worked

2022-06-08 09:15 UTC, mossmaurice approved these changes

2022-06-08 10:49 UTC, merged